### ISSUE TITLE
Build Your First Unlocked Package

### ISSUE THREAD

**Issue by jasonmatos** [dreamhouseapp/dreamhouse-sfdx#25]
Trying to create a version using : 
`sfdx force:package2:version:create --directory force-app --wait 10`

Followed all steps from Trailhead module Build Your First Unlocked Package (https://trailhead.salesforce.com/trails/sfdx_get_started/modules/unlocked-packages-for-customers/units/build-your-first-unlocked-package?trailmix_creator_id=00550000006FetYAAS&trailmix_id=salesforce-dx)

I'm getting the error
`ERROR:  An unexpected error occurred. Please contact Salesforce Support and provide the following error code: 723076984-9916 (-1373703285).`

I have removed every single elements under the force-app folder with the exception of the Dreamhouse_Settings__c object. At this point I was able to create a version.

Thanks

**Comment by jeffgarbers** [comment]
I'm having a similar issue -- trying to create the package version results in a series of up to 10 timeout and retries, usually followed by the error reported above.

**Comment by prsam** [comment]
I'm having a similar issue. can you please fix this.

**Comment by muenzpraeger** [comment]
It is an issue with reports and dashboards. The team is currently working on a server-side fix.

If you want to proceed with the Trailhead module it should work by removing the _reports_ and the _dashboard_ folder.

**Comment by MuriloKakazu** [comment]
Seems to be working now.

**Comment by javansoliday** [comment]
Here is the error I am getting:

Property_Explorer: You must have My Domain deployed to use component c:PageTemplate_2_7_3.,Property_Finder: In field: flexiPage - no FlexiPage named Property_Finder found,Property_Explorer: In field: flexiPage - no FlexiPage named Property_Explorer found,Property_Finder: You must haveMy Domain deployed to use component c:PageTemplate_2_6_4.,DreamHouse: In field: tab - no CustomTab named Property_Finder found,dreamhouse: In field: tab - no CustomTab named Property_Explorer found.

**Comment by muenzpraeger** [comment]
@javansoliday As the error says you must have My Domain deployed to your org.

https://trailhead.salesforce.com/en/content/learn/modules/identity_login/identity_login_my_domain

**Comment by Antoine0707** [comment]
![image](https://user-images.githubusercontent.com/45604410/51597193-f0ac6d00-1efa-11e9-9915-1898691cc81f.png)
I do nothing, just restart command ... there is a reason ?

**Comment by javansoliday** [comment]
Thanks. I fixed this.


JAVAN SOLIDAY
Software Development









ForeTees.com <http://foretees.com/>

**Comment by Antoine0707** [comment]
how do you fix it ? 
you have just create a subdomain ? I don't understand why a simple tutorial from dreamhouse ask us to create a subdomain

**Comment by javansoliday** [comment]
It did require the domain name. I’m not sure why they did that but that was what caused the issue.


JAVAN SOLIDAY

**Comment by Antoine0707** [comment]
OK Thanks Javan

**Comment by zzj8810** [comment]
still have the issue 
>ee381913noair:dreamhouse-sfdx aa381913$ sfdx force:package:version:create -p th-dreamhouse -d force-app -k test1234 --wait 10 -v DevHub2
>Request in progress. Sleeping 30 seconds. Will wait a total of 600 more seconds before timing out. Current Status='Queued'
>Request in progress. Sleeping 30 seconds. Will wait a total of 570 more seconds before timing out. Current Status='InProgress'
>Request in progress. Sleeping 30 seconds. Will wait a total of 540 more seconds before timing out. Current Status='InProgress'
>ERROR running force:package:version:create:  Property_Explorer: You must have My Domain deployed to use component c:PageTemplate_2_7_3.,Property_Finder: In field: flexiPage - no FlexiPage named Property_Finder found,Property_Explorer: In field: flexiPage - no FlexiPage named Property_Explorer found,Property_Finder: You must have My Domain deployed to use component c:PageTemplate_2_6_4.,DreamHouse: In field: tab - no CustomTab named Property_Finder found,dreamhouse: In field: tab - no CustomTab named Property_Explorer found

**Comment by CamiloFBL** [comment]
I'm trying to complete "Build an Automated CI/CD Pipeline with GitLab" module and I'm not able to successfully pass the testing, so obviously GitLab won't deploy. This is the message (This module generate scratch orgs):
```
=== Failures
FULLNAME                                        MESSAGE
──────────────────────────────────────────────  ─────────────────────────────────────────────────────────────────────────────────────────────────
RejectDuplicateFavoriteTest.acceptNonDuplicate  System.AssertException: Assertion Failed
                                                /builds/Rykum/DreamHouse-sfdx/force-app/main/default/classes/RejectDuplicateFavoriteTest.cls:29:1

=== Test Summary
NAME                 VALUE
───────────────────  ────────────────────────────────────────────────────────
Outcome              Failed
Tests Ran            38
Passing              37
Failing              1
Skipped              0
Pass Rate            97%
Fail Rate            3%
Test Start Time      Oct 17, 2019 5:17 PM
Test Execution Time  5585 ms
Test Total Time      5585 ms
Command Time         6878 ms
Hostname             https://***********.my.salesforce.com/
Org Id               00D560000************
Username             *************@example.com
Test Run Id          7075600************
User Id              00556000***************
Test Run Coverage    87%
Org Wide Coverage    77%

ERROR: Job failed: exit code
```
Anything I can do to fix it?
