### ISSUE TITLE
Errors installing as a package

### ISSUE THREAD

**Issue by DeltaIndiana** [dreamhouseapp/dreamhouse-sfdx#39]
Hi
I've been doing the trailhead module [Build Your First Unlocked Package](https://trailhead.salesforce.com/trails/sfdx_get_started/modules/unlocked-packages-for-customers/units/build-your-first-unlocked-package)  and when I install dreamhouse into my trailhead playground as a released package I get this error:

ERROR:  Encountered errors installing the package!,Installation errors:
1) (Property__c-Property Layout) The ActionId specified was invalid for ActionType QuickAction., Details: Property__c-Property Layout: The ActionId specified was invalid for ActionType QuickAction.
ERROR:  Installation errors:
1) (Property__c-Property Layout) The ActionId specified was invalid for ActionType QuickAction., Details: Property__c-Property Layout: The ActionId specified was invalid for ActionType QuickAction.

Do you have any ideas please?

**Comment by DeltaIndiana** [comment]
I created a new playground org and it installed successfully.

**Comment by prasanth6228** [comment]
Try to active notes and Chatter

**Comment by preetibalalia1709** [comment]
After activation notes and Chatter, still facing the same issue. Working fine in playground org but not in sandboxes. Any ideas?
