### ISSUE TITLE
DreamBot Chat: Text field not cleared after sending message

### ISSUE THREAD

**Issue by mssksg** [dreamhouseapp/dreamhouse-sfdx#42]
When sending a message to the DreamBot, the text field is not cleared after sending the message.

**Comment by muenzpraeger** [comment]
That behaviour is working as designed.

**Comment by mssksg** [comment]
Okay, interesting.
What's the reason for designing the behaviour in that way?

**Comment by muenzpraeger** [comment]
Because it's a sample application where people can experience and test functionality. By leaving the input in the field people can modify i. e. a previous typed or voice input manually, instead of re-doing the data entry completely.
