### ISSUE TITLE
Failed package creation: Property 'status' not valid in version 43.0

### ISSUE THREAD

**Issue by mzanini** [dreamhouseapp/dreamhouse-sfdx#57]
Going through the [Build your first unlocked package](https://trailhead.salesforce.com/content/learn/modules/unlocked-packages-for-customers/build-your-first-unlocked-package?trail_id=sfdx_get_started) module. When creating the package, SFDX returns this error: ``` ERROR:  Opportunity_Status_Change: Property 'status' not valid in version 43.0,Advertise_New_Property: Property 'status' not valid in version 43.0,Post_Price_Changes_to_Slack: Property 'status' not valid in version 43.0,Price_Change_Push_Notification: Property 'status' not valid in version 43.0. ```

**Comment by zaynelt** [comment]
Hey Marco, those errors indicate you're trying to create a package using an older API version (API 43.0). The master branch of this repo stays in sync with the latest release, which maps to API 44.0. The unit you linked to has instructions about modifying the sample sfdx-project.json to match the current release (just after the sample code).

**Comment by mzanini** [comment]
ok thanks!

**Comment by maune** [comment]
It's still 43.0 in the french version of the course module for exemple so the mistake may happen easily.
