### ISSUE TITLE
package creation command not working

### ISSUE THREAD

**Issue by jayabalanj1983** [dreamhouseapp/dreamhouse-sfdx#62]
Trying to create a package as per the command provided in the module returns error 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

The command used to create a package is sfdx force:package:create -n th-dreamhouse -d "My DreamHouse Package" -t Unlocked -r force-app -v DevHub

**Comment by muenzpraeger** [comment]
And also if you use bash or cmd.

**Comment by muenzpraeger** [comment]
No response. Closing the issue.
