### ISSUE TITLE
Create package is not working

### ISSUE THREAD

**Issue by OmarBenitezL** [dreamhouseapp/dreamhouse-sfdx#64]
When I try to run the command:
`sfdx force:package:version:create -p th-dreamhouse -d force-app -k test1234 --wait 10 -v DevHub
`
I got:
`ERROR:  Advertise_New_Property: Property 'status' not valid in version 43.0,Opportunity_Status_Change: Property 'status' not valid inversion 43.0,Post_Price_Changes_to_Slack: Property 'status' not valid in version 43.0,Price_Change_Push_Notification: Property 'status' not valid in version 43.0.`

**Comment by muenzpraeger** [comment]
Can you please check if you’re local repo is current with a `git pull`? It looks like you’re on an outdated version.

**Comment by OmarBenitezL** [comment]
It is up to date: 

git clone https://github.com/dreamhouseapp/dreamhouse-sfdx.git

<img width="999" alt="captura de pantalla 2018-12-14 a la s 09 34 40" src="https://user-images.githubusercontent.com/37809826/50012230-b5299500-ff83-11e8-9bef-1b26135766ba.png">

am I doing something wrong? This is the trailhead that I am trying to complete:
https://trailhead.salesforce.com/content/learn/modules/unlocked-packages-for-customers/build-your-first-unlocked-package

**Comment by zaynelt** [comment]
Can you confirm that the local copy of the sfdx-project.json file has an API version of 44, and confirm that running `sfdx plugins --core` returns a version of the 'salesforcedx' plugin that's at least 44? The error that's displaying in your terminal output is due to an incorrect API version setting. This can come from a dirty clone of the repo, or an out-of-date CLI plugin.

**Comment by OmarBenitezL** [comment]
I am using 43.0 on sfdx-project.json, it is marked on the trailhead:

```
{
   "packageDirectories": [
      {
         "path": "force-app",
         "default": true,
         "package": "dreamhouse",
         "versionName": "Version 1.0",
         "versionNumber": "1.0.0.NEXT"
      }
   ],
   "namespace": "",
   "sfdcLoginUrl": "https://login.salesforce.com",
   "sourceApiVersion": "43.0",
   "packageAliases": {
      "dreamhouse": "0Hoxxx"
   }
}
```
<img width="475" alt="captura de pantalla 2018-12-14 a la s 09 56 20" src="https://user-images.githubusercontent.com/37809826/50013377-97a9fa80-ff86-11e8-8284-27c4b62f8e0e.png">

do I have to use the 44 insted of 43.0?

**Comment by zaynelt** [comment]
Yes. You should use the sfdx-project.json that's in the current master branch of this repo--that should resolve your issue.

**Comment by OmarBenitezL** [comment]
Thanks a lot, it is working! :)
