### ISSUE TITLE
LWC not SFDX edition in App Gallery

### ISSUE THREAD

**Issue by wilsonmar** [dreamhouseapp/dreamhouse-sfdx#66]
The title of this repo is "Salesforce Sample App part of the sample gallery. ..."
However, in the Salesforce app gallery at https://trailhead.salesforce.com/en/sample-gallery
when I click on the Dreamhouse app, I am taken to 
https://github.com/dreamhouseapp/dreamhouse-lwc
rather than this repo containing Aura components.

**Comment by muenzpraeger** [comment]
The link is correct. Both repos support Salesforce DX.

**Comment by muenzpraeger** [comment]
Also the focus of the Sample Gallery is to highlight the newest developments for Salesforce developers, which is the focus of this repo (Lightning Web Components). You can still get to the Aura version using the link provided in the readme file.
