### ISSUE TITLE
No automatic enrichment of the 'packageAliases' section with the package version when creation became asynchronous

### ISSUE THREAD

**Issue by jmsfez** [dreamhouseapp/dreamhouse-sfdx#68]
In the Trailhead "Build Your First Unlocked Package", the package version creation was too long and ended with the following:
![image](https://user-images.githubusercontent.com/28300202/51848429-dd940580-231d-11e9-9396-1161d9c4b26b.png)
Then, I ran the specified command which show me that the creation succeed:
![image](https://user-images.githubusercontent.com/28300202/51848493-fa303d80-231d-11e9-979b-77bb14458982.png)
However, the 'packageAliases' section has not been enriched with "dreamhouse@1.0.0-1": "04t1t000002zuGbAAI"
![image](https://user-images.githubusercontent.com/28300202/51848563-1af89300-231e-11e9-896d-5ba517b33f75.png)
Suppose I enrich it myself, should I succeed to finish the Trailhead Module?
Thanks in advance for your help,
Best regards.

**Comment by muenzpraeger** [comment]
Yes, you can just add that. It's freely editable as you like.
