### ISSUE TITLE
Apex Test faillure (RejectDuplicateFavoriteTest.acceptNonDuplicate)

### ISSUE THREAD

**Issue by JeroenSfdc** [dreamhouseapp/dreamhouse-sfdx#74]
While executing the Gitlab pipeline for this Trailhead module https://trailhead.salesforce.com/content/learn/projects/automate-cicd-with-gitlab/package-your-app-and-automate-cicd, `RejectDuplicateFavoriteTest.acceptNonDuplicate` failed. 

`=== Failures
FULLNAME                                        MESSAGE
──────────────────────────────────────────────  ──────────────────────────────────────────────────────────────────────────────────────────────────────
RejectDuplicateFavoriteTest.acceptNonDuplicate  System.AssertException: Assertion Failed
                                                /builds/JeroenSfdc/[MASKED]-sfdx/force-app/main/default/classes/RejectDuplicateFavoriteTest.cls:29:1`

**Comment by muenzpraeger** [comment]
I don't know the GitLab module. But from the error message it appears that your test is throwing an exception, which you can inspect in your org.

**Comment by JeroenSfdc** [comment]
Hi @muenzpraeger - Trailhead module = https://trailhead.salesforce.com/content/learn/projects/automate-cicd-with-gitlab/package-your-app-and-automate-cicd
I'm running of a brand new playground. Test is run on scratch org during CI.
Will do some more debugging. Only got around by commenting the assertions in the RejectDuplicateFavoriteTest class.

**Comment by JeroenSfdc** [comment]
Ok - I found the culprit @muenzpraeger. The test method creates a user for the 'Standard User' profile. However, my scratch org is being spun up for the Dutch language. Hence, no Profile with name = 'Standard User' is existing, but instead the Profile name = 'Standaardgebruiker'. Unfortunately the Profile object has no API name to query for. The interesting bit here is, that the Playground (which is the Devhub as well) is setup in English. But when CI/CD sources a scratch-org, it's spun up in NL instead of EN. Unlikely I'll be the only once having this issue.

**Comment by muenzpraeger** [comment]
@JeroenSfdc I‘ll created an internal ticket for that. I guess the location in your DevHub is set up for NL, which controls the language.

**Comment by benjaminloerincz** [comment]
Same here. 'Standardbenutzer' instead of 'Standard User'.  You can set "language": "en_US" in project-scratch-def.json to "solve" this.
