### ISSUE TITLE
Build Your First Unlocked Package

### ISSUE THREAD

**Issue by AllanOricil** [dreamhouseapp/dreamhouse-sfdx#81]
When Im trying to create the version of the package Im getting an error.
![image](https://user-images.githubusercontent.com/55927613/65821125-63f44480-e229-11e9-980c-cba73e64daed.png)

Could you help me with that? Im building the package and version with Api 44.0

**Comment by muenzpraeger** [comment]
The current version uses `45.0`, that‘s the one to use.

**Comment by AllanOricil** [comment]
> The current version uses `45.0`, that‘s the one to use.

It is better if you update the trailhead module to say that it uses 45.0 
https://trailhead.salesforce.com/en/content/learn/modules/unlocked-packages-for-customers/build-your-first-unlocked-package

**Comment by muenzpraeger** [comment]
Step 4 mention that the value of `sourceApiVersion` should be set to the current version of the Salesforce CLI. ;-)

**Comment by AllanOricil** [comment]
> Step 4 mention that the value of `sourceApiVersion` should be set to the current version of the Salesforce CLI. ;-)

Isn't the current stable version 46.0? I tried it too before opening this issue and did not work either. It outputed more errors than 44.0.

Also, I finished to run using 45.0 and it outputed other errors as well. I recreated the package using 45.0 and then created a version out of it using api 45.0 too.
![image](https://user-images.githubusercontent.com/55927613/65821622-c8b29d80-e22f-11e9-936c-76a92d513dc6.png)

With API 46.0 it gives me the following errors.
![image](https://user-images.githubusercontent.com/55927613/65821630-f861a580-e22f-11e9-8da8-8804f41fc478.png)

**Comment by AllanOricil** [comment]
I was able to create the version after deleting the references of Einstein_Vision outputed in the terminal. Somehow the package version could not be created with APIs 44.0, 45.0 and 46.0 with those Einstein_Vision references. I removed the tab and its references in the DreamHouse App and dreamhouse permission set. Then I was able to create the version without any problem. 

![image](https://user-images.githubusercontent.com/55927613/65821830-dddcfb80-e232-11e9-8b21-7e80281563a4.png)

Could you help me to understand why this error happened? Thank you.

**Comment by muenzpraeger** [comment]
Can it be that you run an old clone of the repo?

Because there are references in your error message that point to the `mobileReady` metadata tag. And they got removed some time ago, like [here](https://github.com/dreamhouseapp/dreamhouse-sfdx/pull/78).

**Comment by AllanOricil** [comment]
> Can it be that you run an old clone of the repo?
> 
> Because there are references in your error message that point to the `mobileReady` metadata tag. And they got removed some time ago, like [here](https://github.com/dreamhouseapp/dreamhouse-sfdx/pull/78).

I cloned the repo that was in the trailhead module. 
They just say to use it without changing to any branch 
```git clone https://github.com/dreamhouseapp/dreamhouse-sfdx.git```
I only got the ```mobileReady``` error when I tried to create a version with **API 46.0** 
while using the **APIs 44.0** and **45.0** I did not. 
But to create the version with these two APIs I had to get rid of the Einstein_Vision references.

**Comment by muenzpraeger** [comment]
Does your `Broker__c` CustomTab metadata contain the `mobileReady` tag?

**Comment by AllanOricil** [comment]
> `mobileReady`

Yes. 
```
<?xml version="1.0" encoding="UTF-8"?>
<CustomTab xmlns="http://soap.sforce.com/2006/04/metadata">
    <customObject>true</customObject>
    <mobileReady>false</mobileReady>
    <motif>Custom84: Presenter</motif>
</CustomTab>
```

**Comment by muenzpraeger** [comment]
Then you’re local repo is out of date. That got removed some months ago for the Summer release.

https://github.com/dreamhouseapp/dreamhouse-sfdx/pull/78/files

**Comment by AllanOricil** [comment]
> Does your `Broker__c` CustomTab metadata contain the `mobileReady` tag?

Yes, you are right. My local project is using the Spring 18 branch, which I think is correlated to the API 44.0. But the problem is that I just used the cloned command listed in the trailhead module and it checkout automatically to the Spring 18.  I think they did that on porpouse so I could use the API 44.0. I don't know.

![image](https://user-images.githubusercontent.com/55927613/65829843-8164f500-e2a1-11e9-8434-78b9ca39cbb4.png)

I will checkout to the master branch and try to build the package again with the API 46.0, instead of the 44.0.

**Comment by muenzpraeger** [comment]
There is only one branch (master), as we keep that always clean and current based on the actual release. My guess is you may had that already local, older clone.

**Comment by AllanOricil** [comment]
> Then your local repo is out of date. That got removed some months ago for the Summer release.
> 
> https://github.com/dreamhouseapp/dreamhouse-sfdx/pull/78/files

Yes, that's what happened. I will try again here and update you if I have any errors.

**Comment by AllanOricil** [comment]
> There is only one branch (master), as we keep that always clean and current based on the actual release. My guess is you may had that already local, older clone.

It worked as you told. Thank you.

I added you on Linkedin. I would like to talk to you about a question that I have about management of Managed packages. Can we talk there? Thanks
